export default {
  theme: {
    primary: '#0f172a',
    text: '#0f172a',
    subtle: '#475569',
    accent: '#f97316',
    background: '#fff7ed',
    muted: '#fef3c7',
  },
  hero: {
    label: 'Edição limitada',
    badge: 'Produto oficial',
    title: 'SmartBottle Pulse',
    description: 'A garrafa inteligente que lembra você de beber água, monitora sua rotina e mantém a hidratação perfeita durante todo o dia.',
    bullets: [
      'Sensor térmico e de ingestão integrado',
      'Sincroniza via Bluetooth com iOS e Android',
      'Até 30 dias longe da tomada',
    ],
    stats: [
      { label: 'Clientes felizes', value: '12k+' },
      { label: 'Avaliação média', value: '4,9/5' },
    ],
    price: 'R$ 249',
    oldPrice: 'R$ 299',
    shipping: 'Frete grátis e entrega expressa',
    guarantee: 'Garantia total de 30 dias',
    rating: '4.9 de 5',
    reviews: '+1.200 avaliações verificadas',
    image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=900&q=80',
    ctaPrimary: { label: 'Comprar agora', href: '#comprar' },
    ctaSecondary: { label: 'Ver especificações', href: '#detalhes' },
  },
  highlights: [
    {
      icon: '💧',
      title: 'Sensoriamento de hidratação',
      text: 'Detecta automaticamente cada gole e envia alertas personalizados.',
    },
    {
      icon: '📱',
      title: 'App Premium',
      text: 'Planos de hidratação criados por especialistas e sincronização com Apple Health e Google Fit.',
    },
    {
      icon: '🔋',
      title: 'Bateria de longa duração',
      text: 'Até 30 dias com uma única carga e recarga via USB-C.',
    },
  ],
  lifestyle: {
    title: 'Pensada para acompanhar seu ritmo',
    description: 'Fabricada em aço cirúrgico e com isolamento a vácuo, a SmartBottle mantém a temperatura ideal por até 24h. Ideal para rotinas intensas e treinos ao ar livre.',
    bullets: [
      'Compatível com suportes de bike e academia',
      'Revestimento antiderrapante e pegada ergonômica',
      'LED inteligente com alertas discretos',
    ],
    image: 'https://images.unsplash.com/photo-1504805572947-34fad45aed93?auto=format&fit=crop&w=900&q=80',
  },
  bundles: [
    {
      id: 'kit-essencial',
      name: 'Kit Essencial',
      description: '1 SmartBottle + acesso Premium 6 meses',
      price: 'R$ 249',
      oldPrice: 'R$ 299',
      badge: 'Mais vendido',
      delivery: 'Envio imediato',
      benefits: ['1 SmartBottle Pulse', 'App Premium 6 meses', 'Cabo USB-C magnético'],
    },
    {
      id: 'kit-performance',
      name: 'Kit Performance',
      description: '2 SmartBottle + acesso Premium 1 ano',
      price: 'R$ 439',
      oldPrice: 'R$ 548',
      badge: 'Economize 20%',
      delivery: 'Frete express gratuito',
      benefits: ['2 SmartBottle Pulse', 'App Premium 12 meses', 'Suporte de treino incluso'],
    },
    {
      id: 'kit-equipe',
      name: 'Kit Equipe',
      description: '4 SmartBottle + painel corporativo',
      price: 'R$ 829',
      oldPrice: 'R$ 1.196',
      badge: 'Para times',
      delivery: 'Pronta-entrega',
      benefits: ['4 SmartBottle Pulse', 'App Premium 18 meses', 'Painel com relatórios e suporte prioritário'],
    },
  ],
  socialProof: {
    badge: 'Visto em',
    text: 'Seleção das principais publicações em tecnologia e bem-estar.',
    logos: ['TechCrunch', 'Fast Company', 'The Verge', 'Forbes', 'GQ'],
  },
  testimonials: [
    {
      name: 'Mariana Lopes',
      location: 'São Paulo',
      quote: 'Nunca consegui manter o hábito de beber água. Com a SmartBottle meus alertas são personalizados e o app me motiva todos os dias.',
      rating: 5,
    },
    {
      name: 'João Victor',
      location: 'Curitiba',
      quote: 'Produto premium de verdade. A bateria dura muito e o material é impecável. Já virei fã!',
      rating: 5,
    },
    {
      name: 'Gabriela Amaral',
      location: 'Recife',
      quote: 'Comprei o kit performance para mim e para meu parceiro. Acompanhamos tudo pelo painel compartilhado.',
      rating: 5,
    },
  ],
  guarantee: {
    title: 'Compra sem risco',
    description: 'Experimente por 30 dias. Se não se apaixonar, devolvemos 100% do valor.',
    bullets: ['Devolução gratuita', 'Garantia estendida de 2 anos', 'Suporte humanizado 24/7'],
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80',
  },
  faq: [
    {
      question: 'A SmartBottle é à prova d’água?',
      answer: 'Sim. Ela possui vedação IP67 e pode ser lavada normalmente. Apenas evite submergir o módulo de carregamento.',
    },
    {
      question: 'Preciso pagar assinatura?',
      answer: 'O app Premium tem 6 meses inclusos no kit essencial. Depois desse período a assinatura é opcional.',
    },
    {
      question: 'Qual o prazo de entrega?',
      answer: 'Enviamos de São Paulo em até 24h úteis. O prazo médio é de 2 a 5 dias úteis dependendo da região.',
    },
  ],
  footer: {
    note: 'SmartBottle Pulse © 2025 — Frete grátis e garantia total em todo o Brasil.',
  },
};
